# Project Name
TARGET = Pedal

# Sources
CPP_SOURCES = Pedal.cpp

# Library Locations
LIBDAISY_DIR = ../Documents/Eudyptula/libDaisy/
DAISYSP_DIR = ../Documents/Eudyptula/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
